/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yokai' at '10/20/16 2:32 PM' with Gradle 2.13
 *
 * @author yokai, @date 10/20/16 2:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
